environment:
  msvs_toolset: 14
  BOOST_VERSION: 60
  FASTBUILD: 1
  matrix:
    - platform: x64
      configuration: Release

os: Visual Studio 2015

#shallow_clone: true
# limit clone to latest 5 commits
clone_depth: 5

services:
  - postgresql94 #if changing this, also change PATH below

install:
  - SET PGUSER=postgres
  - SET PGPASSWORD=Password12!
  - SET PATH=C:\Program Files\PostgreSQL\9.4\bin\;%PATH%

build_script:
  - scripts\build-appveyor.bat

after_build:
  - 7z a mapnik-visual-images.zip C:\tmp\mapnik-visual-images

artifacts:
  - path: mapnik-gyp\msbuild-summary.txt
    name: msbuild-summary.txt
  - path: mapnik-gyp\msbuild-errors.txt
    name: msbuild-errors.txt
  - path: mapnik-gyp\msbuild-warnings.txt
    name: msbuild-warnings.txt
  - path: mapnik-visual-images.zip
    name: mapnik-visual-images.zip

test: off
deploy: off
